### ISSUE TITLE
Torch & CUDA

### ISSUE THREAD

**Issue by mwylerCH** [hubner-lab/GWANN#10]
Thanks for developing GWANN.
I try to run it, I can simulate and train. However, once I go for the real data I got the following issue:

```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. 
If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

What's the solution? Of course I'm running the command with the ```--cpu``` flag.
Many thanks

**Comment by martin-migal** [comment]
Thank you for the feedback.
I've updated the code per the error message. That said, this likely is a system specific issue, thus I'm not able to replicate the error to verify the fix works. Can you please give it a go?

**Comment by mwylerCH** [comment]
Many thanks for the answer. Something worked, the error changed into 
```
python GWANN.py run \
> --vcf $TEMPDIR/subset.vcf \
> --pheno $TEMPDIR/phenoFile.csv \
> --trait TRAIT \
> --output $TEMPDIR/primo \
> --model $TEMPDIR/GWANN/models/model.pt \
> --cpu
save vcf
reload vcf
parse vcf
final_vcf torch.Size([5536, 242])
n_snps 5536
Traceback (most recent call last):
  File "GWANN.py", line 610, in <module>
    cli()
  File "/home/mwyler/miniconda3/envs/Py3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mwyler/miniconda3/envs/Py3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mwyler/miniconda3/envs/Py3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mwyler/miniconda3/envs/Py3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mwyler/miniconda3/envs/Py3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "GWANN.py", line 157, in run
    net.load_state_dict(torch.load(model,torch.device(device))['model_state_dict'])
  File "/home/mwyler/miniconda3/envs/Py3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Net:
	Missing key(s) in state_dict: "lin_seq.2.weight", "lin_seq.2.bias". 
	Unexpected key(s) in state_dict: "lin_seq.3.weight", "lin_seq.3.bias". 
```

Now I don't know which specific information you need. I'm running it in a conda env with python 3.8. The installation is made with git clone, as described. The machine runs on ubuntu 16.04 (shame on me).

**Comment by martin-migal** [comment]
Thank you for bringing this to our attention. 
This issue is with the saved model found in the git (rather with the algorithm or code) and we're looking into it.
