### ISSUE TITLE
error

### ISSUE THREAD

**Issue by m-jahani** [hubner-lab/GWANN#4]
Hi, 

Thanks for the deep learning algorithm GWAS tool, 

I have successfully installed GWANN and all its requirements. However, I am facing some errors when I run the script:

 > python3 GWANN.py run --vcf Annuus.ann_fullsam.tranche90_snps_bi_AN50_beagle_AF99.vcf.gz --pheno test.csv -t test_pheno --model models/net-accuracy.pt --output output_test

and it is the error message:

> /home/mjahani/miniconda3/envs/mypython3/lib/python3.9/site-packages/allel/io/vcf_read.py:1736: UserWarning: multiple INFO > > headers for 'AF'
>   warnings.warn('multiple INFO headers for %r' % k)
> (4882662, 287)
> Traceback (most recent call last):
>   File "/home/mjahani/miniconda3/envs/mypython3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
>  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'sample'
> 
> The above exception was the direct cause of the following exception:
> 
>  Traceback (most recent call last):
>   File "/home/mjahani/bin/GWANN/GWANN.py", line 579, in <module>
>     cli()
>  File "/home/mjahani/miniconda3/envs/mypython3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
>    return self.main(*args, **kwargs)
>   File "/home/mjahani/miniconda3/envs/mypython3/lib/python3.9/site-packages/click/core.py", line 1053, in main
>     rv = self.invoke(ctx)
>   File "/home/mjahani/miniconda3/envs/mypython3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/mjahani/miniconda3/envs/mypython3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/mjahani/miniconda3/envs/mypython3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/mjahani/bin/GWANN/GWANN.py", line 131, in run
>     _,index_samples,_ = np.intersect1d(vcf_samples,pheno["sample"],return_indices=True)
>  File "/home/mjahani/miniconda3/envs/mypython3/lib/python3.9/site-packages/pandas/core/frame.py", line 3458, in __getitem__
>    indexer = self.columns.get_loc(key)
>  File "/home/mjahani/miniconda3/envs/mypython3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
>     raise KeyError(key) from err
> KeyError: 'sample'

Any idea what can be wrong?

Thanks

**Comment by NimrodAshkenazy** [comment]
It seems that the phenotype CSV file is missing a column named "sample" with the corresponding vcf samples.

**Comment by martin-migal** [comment]
Example phenotype CSV added. Error message when "sample" field is missing.
